### ISSUE TITLE
Chiffres romains

### ISSUE THREAD

**Issue by Opahl** [nobe4/prolog#1]
Ca provient d'internet, j'ai trouvé ça en Anglais et je l'ai "traduit" 

chiffre(i, 1).
chiffre(v, 5).
chiffre(x, 10).
chiffre(l, 50).
chiffre(c, 100).
chiffre(d, 500).
chiffre(m, 1000).

conversion(Romain, Normal) :- conversion(Romain, 0, Normal).

conversion([], X, X).

conversion([A], X, Normal) :-
    chiffre(A, AVal),
    Normal is X + AVal.

conversion([A, B | Queue], X, Normal) :-
    chiffre(A, AVal), chiffre(B, BVal),
    AVal < BVal,
    NewX is X + BVal - AVal,
    conversion(Queue, NewX, Normal).

conversion([A, B | Queue], X, Normal) :-
    chiffre(A, AVal), chiffre(B, BVal),
    AVal >= BVal,
    NewX is X + AVal,
    conversion([B | Queue], NewX, Normal).

```
tests: conversion([v, i, i], Normal).
```

**Comment by nobe4** [comment]
closed by f80b47fda33c7f811d82ec38490c7a94a450b79b
